name: deploy

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Retrieve github tag
        id: github_tag
        run: echo ::set-output name=RESULT::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Prepare deploy
        run: |
          cat <(echo -e "${{ secrets.GPG_KEY_CONTENTS }}") | gpg --batch --import
      - name: Deploy with Maven
        run: mvn --no-transfer-progress --batch-mode -Drevision=${{ steps.github_tag.outputs.RESULT }} -Dgpg.passphrase=${{ secrets.SIGNING_PASSWORD }} -s settings.xml -T 1C -Pdeploy -DskipTests=true -Dmaven.test.skip clean deploy
        env:
          OSSRH_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}