name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Gradle packages
        uses: burrunan/gradle-cache-action@v1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Retrieve github tag
        id: github_tag
        run: echo ::set-output name=RESULT::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Publish with Gradle
        run: ./gradlew publish --no-parallel --no-daemon --build-cache -Pgithub.tag=${{ steps.github_tag.outputs.RESULT }} -Pgpr.user=${{ github.actor }} -Pgpr.password=${{secrets.GITHUB_TOKEN}}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: ${{ endsWith(github.ref, '-SNAPSHOT') }}
